### PR TITLE
[NEW] LiteSpeed cache plugin comaptibility

### PR DESCRIPTION
**Pull request by hailite**
Support LiteSpeed Cache plugin with ESI nonce

### CODE REVIEW

**Comment by Shelob9** [comment]
For #1968

**Comment by Shelob9** [comment]
@hailite This looks good. I like having this conditional logic in place vs a filter.

Before I merge, can you confirm this solves the compatibility issue? I have no way to test.

Besides that and inline doc issues (I'll fix after merge) looks fine to me.

**Comment by hailite** [comment]
Yes, this is from my test code with your plugin and our pre release version, which is on https://github.com/litespeedtech/lscache_wp/tree/master/litespeed-cache

**Comment by hailite** [comment]
Please tell the version this can be added, so we can add your plugin into our compatible list.

If you want, you can add us too.

Thanks.

**Comment by Shelob9** [comment]
@hailite This is now merged and will be included in Caldera Forms 1.5.6.2. Thanks for your help.

**Comment by hailite** [comment]
Gotcha. Thanks.

**Pull request merged**
