### PR TITLE
Caldera Forms 1.8.2

### PR DESCRIPTION
**Pull request by Shelob9**
Blockers -
- [x] #3051
- [x] #3060

### CODE REVIEW

**Comment by Shelob9** [comment]
I want to get 1.8.2 out tomorrow with the Yoast fix. That has been tested.

I left issues with approved PRs on this milestone. If @swapnilmanjrekar was here this week, I'd merge all of those to another branch and ask him to QA them. Not sure if beacuse they are tested and reviewed we (@New0 ) should merge them all to develop and release tomorrow or punt them to 1.8.3 to be released next week.

**Comment by Shelob9** [comment]
Here is a built version that can be used to test: [1.8.2-rc.3.zip](https://github.com/CalderaWP/Caldera-Forms/files/2938548/1.8.2-rc.3.zip) 

Changelog can be reviewed here: https://github.com/CalderaWP/Caldera-Forms/pull/3052/commits/3976653d3494d9a9c6faf469a61d6ff17c3afed8#diff-eb6b6c90251ab33cee784713c451e6d8R794

**Comment by paaljoachim** [comment]
Hey Josh

I installed rc3 on the client dev site.

I noticed that the Slider values now show correctly.
https://github.com/CalderaWP/Caldera-Forms/issues/3040

I am getting the following Console error message:

Uncaught TypeError: Cannot read property 'data' of undefined
    at 2e828.js:325
    at Object.calderaForms (2e828.js:325)
    at e (2e828.js:325)
    at Object.calderaForms (2e828.js:325)
    at e (2e828.js:325)
    at Object.calderaForms (2e828.js:325)
    at e (2e828.js:325)
    at calderaForms (2e828.js:325)
    at 2e828.js:325
(anonymous) @ 2e828.js:325
calderaForms @ 2e828.js:325
e @ 2e828.js:325
calderaForms @ 2e828.js:325
e @ 2e828.js:325
calderaForms @ 2e828.js:325
e @ 2e828.js:325
calderaForms @ 2e828.js:325
(anonymous) @ 2e828.js:325

screen shot 2019-03-06 at 23 25 22

**Comment by Shelob9** [comment]
@paaljoachim is there a URL I can go to for your staging site or whatever this is happening on? It would be helpful if I could trigger the issue and set breakpoints.

**Comment by paaljoachim** [comment]
https://celias.no/dev/bestilling/

Here is the order form as well as the calculator with the slider.
I just sent you an e-mail with login information as well.

**Comment by Shelob9** [comment]
Thanks Paal - We opened a new issue and it looks simple: https://github.com/CalderaWP/Caldera-Forms/issues/3060

**Comment by paaljoachim** [comment]
Add a download zip for the fixed version and I will test that as well.
Thanks.

**Comment by New0** [comment]
Hello @paaljoachim , thank you for testing , this is the build with wp-data
[1.8.2.zip](https://github.com/CalderaWP/Caldera-Forms/files/2941905/1.8.2.zip)

**Comment by Shelob9** [comment]
@New0  Manually triggered build did pass https://travis-ci.org/CalderaWP/Caldera-Forms/builds/503145953

**Comment by paaljoachim** [comment]
I have installed it here:
https://celias.no/dev/bestilling/

Here is the error message I am getting now (seems very similar to the last one). To be sure that I am not caching the olde rc-3 version I opened a new private window.

Uncaught TypeError: Cannot read property 'data' of undefined
    at e458b.js:324
    at Object.calderaForms (e458b.js:324)
    at e (e458b.js:324)
    at Object.calderaForms (e458b.js:324)
    at e (e458b.js:324)
    at Object.calderaForms (e458b.js:324)
    at e (e458b.js:324)
    at calderaForms (e458b.js:324)
    at e458b.js:324
h41qiWMcaZa.js:55 ErrorUtils caught an error: "<EX[["Tried to listen to element of type %s from %s: %s","click","Error","C...". Subsequent errors won't be logged; see https://fburl.com/debugjs.
reportError @ h41qiWMcaZa.js:55

Backend:
![screen shot 2019-03-07 at 16 21 35

**Comment by Shelob9** [comment]
@paaljoachim I'm not seeing that in my tests, I wonder if its becuse of your theme?

**Comment by paaljoachim** [comment]
The official release of 1.8.2.

Frontend looks good with the values as earlier mentioned. The error code is the same.
Backend form. I can now see the sliders.

screen shot 2019-03-07 at 23 18 21

Switching from the Avada child theme to Twenty Nineteen .

This error code shows up:
Uncaught TypeError: Cannot read property 'data' of undefined
    at 08754.js:221
    at Object.calderaForms (08754.js:221)
    at e (08754.js:221)
    at Object.calderaForms (08754.js:221)
    at e (08754.js:221)
    at Object.calderaForms (08754.js:221)
    at e (08754.js:221)
    at calderaForms (08754.js:221)
    at 08754.js:221

Turning off all plugins except Caldera Forms and having Twenty Nineteen active this error code shows up:

(index):690 Uncaught ReferenceError: jQuery is not defined
    at (index):690
(anonymous) @ (index):690
b58095211eb021c8205fec388677c610.min.js:3 Uncaught ReferenceError: jQuery is not defined
    at b58095211eb021c8205fec388677c610.min.js:3
(anonymous) @ b58095211eb021c8205fec388677c610.min.js:3
jquery-migrate.min.js?ver=1.4.1:2 JQMIGRATE: Migrate is installed, version 1.4.1
index.min.js?ver=1.8.2:1 Uncaught TypeError: Cannot read property 'SelectControl' of undefined
    at Object.<anonymous> (index.min.js?ver=1.8.2:1)
    at e (index.min.js?ver=1.8.2:1)
    at Object.<anonymous> (index.min.js?ver=1.8.2:1)
    at e (index.min.js?ver=1.8.2:1)
    at index.min.js?ver=1.8.2:1
    at index.min.js?ver=1.8.2:1
(anonymous) @ index.min.js?ver=1.8.2:1
e @ index.min.js?ver=1.8.2:1
(anonymous) @ index.min.js?ver=1.8.2:1
e @ index.min.js?ver=1.8.2:1
(anonymous) @ index.min.js?ver=1.8.2:1
(anonymous) @ index.min.js?ver=1.8.2:1
index.min.js?ver=1.8.2:30 Uncaught TypeError: Cannot read property 'render' of undefined
    at HTMLDocument.<anonymous> (index.min.js?ver=1.8.2:30)
    at HTMLDocument.dispatch (jquery.js?ver=1.12.4:3)
    at HTMLDocument.r.handle (jquery.js?ver=1.12.4:3)
    at Object.trigger (jquery.js?ver=1.12.4:3)
    at Object.a.event.trigger (jquery-migrate.min.js?ver=1.4.1:2)
    at HTMLDocument.<anonymous> (jquery.js?ver=1.12.4:3)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.trigger (jquery.js?ver=1.12.4:3)
    at HTMLFormElement.<anonymous> (caldera-forms-front.min.js?ver=1.8.2:5)

Can be seen here: https://celias.no/dev/bestilling/
I will continue to leave all plugins except Caldera Forms and have Twenty Nineteen active. So that you can take a look if you'd like.

**Comment by vaka2vaka** [comment]
The official release of 1.8.2.   

Caldera  to 1.7.6 my stats show a Total Page size of 3.98 Mb . When i update to 1.8.2 my stats change to a Total Page Size of 6.25Mb . Why does it happen?

**Comment by Shelob9** [comment]
@vaka2vaka I opened a new issue here: https://github.com/CalderaWP/Caldera-Forms/issues/3065

Please add more details there.

**Comment by Shelob9** [comment]
I am locking this to comments. Feel free to open new issues. This PR can not be reopened

**Pull request merged**
