### PR TITLE
Test Cypress in CI

### PR DESCRIPTION
**Pull request by New0**
This also tests the webhook integration for GI tests

### CODE REVIEW

**Comment by Shelob9** [comment]
> This also tests the webhook integration for GI tests
@New0 Why? It's my expectation that the cypress tests replace the Ghost Inspector tests.

**Comment by Shelob9** [comment]
@New0 I'm glad you got this working. I just read through the results and they look like what we want -- I always want to make sure it's actually running tests, not exiting early or something.

You can probably resolve the conflict with `rm yarn.lock && yarn`.

The title of this PR is `Test Cypress in CI` but I think your goal is two items: 1) fix unit and integration tests and 2) Make Cypress.io work in pipeline. Beacuse this satisfies item 1 and is a big win, and item 2 is a big project, please _consider_ merging this without cypress and then opening a new PR called `Test Cypress in CI`.

**Comment by New0** [comment]
@Shelob9 I leave this open to test the work to achieve running cypress in CI , current unit and integration tests were fixed via https://github.com/CalderaWP/Caldera-Forms/pull/3442

**Comment by New0** [comment]
This was worked on using Github actions via - https://github.com/CalderaWP/Caldera-Forms/pull/3575 -

**Pull request closed without merging**
