### PR TITLE
fix(typo): Fix typo in code comment

### LINKED ISSUE #2333: Inline documentation typo in cf_filter_addons_do_filter_addons
#2330 is a PR for this.

### PR DESCRIPTION
**Pull request by raftaar1191**
PR to fix #2333 

Fix typo in code comment section 

image

### CODE REVIEW

**Comment by Shelob9** [comment]
@raftaar1191 Thanks for this pull request. I appreciate it. Also good catch!

I would merge this pull request if it was just the first commit e160e1b59330109fc5094f44a3683d6281520524

Yes, the code formatting is an issue, but it's a separate issue -  #2206

Do you mind reverting the phpcs commit, so this merges more cleanly? Don't worry, I'm going to clean it up :)

**Comment by Shelob9** [comment]
I opened #2333 for this.

**Comment by raftaar1191** [comment]
Sure @Shelob9  I am reverting my [comment](https://github.com/CalderaWP/Caldera-Forms/pull/2330/commits/6dadc8a39a31b4a0788978c3a221a6c9d62c0e5b) for PHPCS in above PR

**Comment by raftaar1191** [comment]
PR updated @Shelob9

**Comment by Shelob9** [comment]
Thanks @raftaar1191

**Pull request merged**
