### PR TITLE
Use output buffering to prevent server-side errors form printing in json response

### PR DESCRIPTION
**Pull request by Shelob9**
Changes made:

* Fix window.cf2 not being an object #2821
* Start output buffering when form submission starts. #2820 #2448 #2788

Not going to  use for admin-ajax usage in admin beacuse then I have to worry about testing that and we're going to rip that all out soon anyway. The entry edit bug  is covered by this PR without doing any of the other admin send jsons.

### CODE REVIEW

**Comment by Shelob9** [comment]
I'm not sure how to test this with automation, but from manually testing I know that if this is wrong, it will break every acceptance test that actually submits the form, so that's a good test.

I added this filter locally:

```
add_action( 'caldera_forms_submit_process_before', function() {
	echo 'aaaa';
	echo $x;
});
```

Before this patch, ajax response would be like `aaaa. NOTICE $x not defined {data: ...}` goal is to only return JSON.

**Comment by Shelob9** [comment]
@New0 Please review and merge if good.

**Comment by regiside** [comment]
I'm running into this #2448 issue. Is this change available for download yet? If not when/how can I get this into my version of Wordpress. Thanks for the help!

**Comment by Shelob9** [comment]
@regiside This will be included in Caldera Forms 1.8. We will release a beta of 1.8 from the develop branch, once it is stable. 1.8 is a major update and it's not ready for use on a real site.

**Comment by regiside** [comment]
Okay thanks, for the time being I've just disabled the Ajax functionality as I was redirecting after form submission anyway. I'll look forward to 1.8!

**Pull request merged**
