### PR TITLE
Make CF2 File field look like Advanced FIle Field 1

### PR DESCRIPTION
**Pull request by New0**
This PR works on points of #2950, these are the main 4 \:

- [x] Make the list of files in the field use the same typography and font/icon sizes as v1.

- [x] When using image preview, replace image name with image preview.

- [x] File size should be listed in kB, MB or GB.

@Shelob9 I agree with all the points, just need to add that the progress bar will require more time

### CODE REVIEW

**Comment by Shelob9** [comment]
@New0 BTW This is the function we're currently using for file size https://github.com/CalderaWP/Caldera-Forms/blob/master/fields/advanced_file/uploader.js#L2

**Comment by New0** [comment]
@Shelob9 I left the button to remove the files a bit bigger than v1, I think it too small to be accessible, could you review and let me know what's missing to check off "Make the list of files in the field use the same typography and font/icon sizes as v1." 

- >Just a reminder to test after flushing browser cache (ctrl + f5 on win), to be sure to load last css

Thanks for the function.

**Comment by Shelob9** [comment]
On the left  is what I see when I 
* checkout this branch at 7f1ade3 
* run `npm run build:webpack`
* Flush browser cache
* add a file to field.

screen shot 2019-01-30 at 9 58 32 am

On the right is a v1 field, same theme. http://dev-caldera-testing.pantheonsite.io/2021-adv-file-created1-5-7-1-dev1-5-8/

I think that the one on the left has the following differences that we should recreate in the new field:
* smaller text
* a space between the X and the name of the file
* a lighter underline
* the file size displayed in menainful units
* the file type and size under the name
* The X looks like something I should click on.

**Comment by Shelob9** [comment]
>I think it too small to be accessible
I checked http://dev-caldera-testing.pantheonsite.io/2021-adv-file-created1-5-7-1-dev1-5-8/ with https://achecker.ca/checker/index.php and it did not raise issues there. Does your testing raise any errors on that?

**Comment by New0** [comment]
@Shelob9 we are facing issue https://github.com/CalderaWP/Caldera-Forms/issues/2947 

At the moment we need to run `npm run build` and after again `grunt` for that Stylesheet to be loaded on frontend. 

This is how I see it 
screenshot_2019-01-30 2944 dev 1

**Comment by Shelob9** [comment]
Ok, if that's what it looks like, that's great. I liked the smaller X, but
if you think it is too small, then that's fine by me.

**Comment by Shelob9** [comment]
> File fields should show a progress indicator when uploading.
Trigger spinner when upload starts -- this is better than v1, where it starts after upload, which could create user confusion as they might not see progress bar.

**Comment by Shelob9** [comment]
@New0 Please resolve conflicts and merge.

**Pull request merged**
