### PR TITLE
#2904 add 'disabled' attribute for Checkbox, Dropdown, and Autocomplete field types

### PR DESCRIPTION
**Pull request by mecachisenros**
This PR adds the `disabled` attribute for the the Checkbox, Dropdown, and Autocomplete field types, as per my comments on #2904

### CODE REVIEW

**Comment by Shelob9** [comment]
@mecachisenros Thanks for this! Looks good to me. We have 2 big PRs for 1.8.0 that are about to land and we can clean up this merge - don't worry about the conflicts until then.

@New0 I'm concerned about sneaking for things on to 1.8.0 because we need to ship, but this one is really simple, as long as it doesn't cause ghost inspector to fail, we should do it in 1.8.0. Let's discuss this tomorrow.

**Comment by mecachisenros** [comment]
Many thanks @Shelob9!

I have one more suggestion/feature request regarding this, which I would like to hear your thoughts/opinion.

When disabling a Radio field’s option the default value (`checked` attribute) is [hard coded](
https://github.com/CalderaWP/Caldera-Forms/blob/master/fields/radio/field.php#L33) to `none/empty`, disabled fields/options are never submitted in a form so for me it doesn’t make sense to hard code it.

This can cause issues when viewing/editing an entry if you have conditionals based on an option and this option’s default has been reset.

I’m happy to add a second commit to this PR or open a separate issue with it’s corresponding PR, but since it’s just removing the `$checked = false` I thought it’s worth asking here.

**Comment by Shelob9** [comment]
>I have one more suggestion/feature request regarding this, which I would like to hear your thoughts/opinion.
Can you please open a new ticket and a new PR for that? One change = one issue, one PR is the ideal.

Also:
We talked about this today - We will merge #2854 and then update this branch, if tests pass, then we'll merge in 1.8.0. If not, we will move it to 1.8.1 milestone and fix it once 1.8.0 is out. Need to ship soon!

**Comment by mecachisenros** [comment]
Many thanks @Shelob9 PR #2914 and issue #2913 created.
I'll give it a go and also run the unit tests myself.

**Comment by Shelob9** [comment]
@New0 Please review now that everything is merged, if it works, merge, if not, we'll re-address in 1.8.1

**Comment by Shelob9** [comment]
Accidental close.

**Comment by New0** [comment]
First test on a threee options checkboxes field breaks \:
[debug.log](https://github.com/CalderaWP/Caldera-Forms/files/2792155/debug.log)

**Comment by mecachisenros** [comment]
@New0 my bad, I've amended it, I made the assumption `$disabled` was defined :-1: 
 
cb229bc should fix it, I've tested locally and ran `composer wp:tests` as well.

**Comment by New0** [comment]
Update for @mecachisenros , sorry it seems like my commit was pushed (I thought it had failed so I requested the changes )

**Comment by New0** [comment]
@Shelob9 this works for me if you want to include it to 1.8.0 again, you can see the Gist example of how to use it at https://gist.github.com/New0/43675dc394fef1510eba33668b7dcf5f

**Comment by Shelob9** [comment]
@new0 I can't think of any reason not to merge for 1.8.0 besides I'm nervous and it isn't related to our 1.8.0 priorities. Checkbox fields, including getting better HTML markup in there finally, could literally be the1.8.1 focus.

If Ghost Inspector and Cypress tests pass and you want to merge for 1.8.0, go ahead, I have no rational reason not to, and want to make Kevin and friend's lives easier.

**Pull request merged**
