### PR TITLE
Target correct file to generate <input> for Color Picker field

### PR DESCRIPTION
**Pull request by New0**
For #1683 

The color picker configuration used the generic-input.php file to generate the <input> for the color picker field when the color picker input works with color_picker/field.php

### CODE REVIEW

**Comment by New0** [comment]
@Shelob9 I have second thoughts about this, was it intentional to target generic-input.php ? Maybe with the idea to set the input attributes in classes/field/input.php

**Comment by kjohnson** [comment]
@New0 looks like @Shelob9 did intentionally change to a generic input, see https://github.com/CalderaWP/Caldera-Forms/commit/254f60eab17c1f03d9ee7ab966ed8d9a884f399e, although this may have been a regression.

**Comment by Shelob9** [comment]
@New0 Right. I wanted to move all input fields to generic input, so that the input's attributes would pass through `caldera_forms_field_attributes` filter.

If @kjohnson is correct here about the class name being the issue - https://github.com/CalderaWP/Caldera-Forms/issues/1683#issuecomment-532763280 - then that filter could be used to fix it. Or maybe this indicates that  `Caldera_Forms_Field_Util::prepare_field_classes()` is defective.

Also, take a look at the `caldera_forms_field_js_color_picker_settings` filter.

**Comment by kjohnson** [comment]
The change to the generic would explain why the render didn't match what I was seeing in the codebase. It could be as simple as the generic isn't setting the correct class attribute - which would have been an understandable oversight without an acceptance test.

**Comment by New0** [comment]
Thank @Shelob9 , yes @kjohnson , it seems like the precise attributes required by the color picker field were not set during the file switch.
It runs through caldera_forms_field_attributes filter hook.
I will add a Ghost Inspector test for the color picker and report before we merge.

**Comment by New0** [comment]
Created test https://app.ghostinspector.com/tests/5def652741fe8157e17697ef

**Pull request merged**
