### PR TITLE
Set bcc/cc properly for caldera forms pro API requests

### PR DESCRIPTION
**Pull request by Shelob9**
#2275

### CODE REVIEW

**Comment by New0** [comment]
@Shelob9 The PR works, however I just noticed that multiple recipients don't work in main recipients field with ot without Pro app activated. Do you want to fix that here or should I open a new issue ?

**Comment by Shelob9** [comment]
New issue and I'm pretty sure that's a new feature. I don't think that ever
worked, but it could.

**Comment by New0** [comment]
Sets correctly multiple recipient in the auto responder Cc and Bcc fields inwhen Pro enhanced delivery is activated.

**Comment by New0** [comment]
I will merge feature/2278 into feature/2275 and push a new PR

**Pull request closed without merging**
