### PR TITLE
Use event object data to set form id for cf2 at cf.ajax.request action

### PR DESCRIPTION
**Pull request by Shelob9**
In 44d0b64 I switched from using `event.currentTarget.activeElement.form.id` which is giving us the error #3021 to `obj.formIdAttr` which should always be set.

@New0 You mentioned in Slack that this is related to #2972 This looks like the change you were refering to: https://github.com/CalderaWP/Caldera-Forms/commit/7e3ac08c12b436e12a648208ad92d999d876fd65#diff-b5c09ff116228d4f36031117e15676e3L73

### CODE REVIEW

**Comment by Shelob9** [comment]
@swapnilmanjrekar Can you please test this PR?

Before beginning, read #2972 as I am worried about reintroducing that bug.

Please checkout this branch in your local development environment. Test form submission in Chrome, Safari and Edge. Please test with two forms:

1) The default contact form.
2) A form with the new advanced file field

Please test with:

1) one of each form on the page
2) Both forms on the page
3) Two of the forms with the advanced file field on the page.

**Comment by swapnilmanjrekar** [comment]
**I checked this PR using the following steps:**

- I created a  WordPress test site on my desktop locally using Lando.
- I installed Caldera Forms plugin on my test site.
- I check out the Caldera Forms plugin from feature/3021 branch.
- I created a contact us form from the available form templates.
- I saved the created contact us form.
- Next, I created a form with one advanced file field v2.0 field and submit button.
- I saved the created form.
- Next, I Started testing for 3 Test Scenarios.:

1. **One of each form on the page:**

- I checked this on my local Lando WordPress test site.
- In my WordPress Test Site, Under Pages Section, I created a Page.
- In that page, I gave it name One of each form.
- Using the block editor, I added the already created Contact Form from CF plugin.
- I Saved and loaded the page.
- I entered all the details in my contact form and submitted form successfully.
- Page with Contact Form was submitted successfully and it was as per my expectations.
- Similarly, I performed the above steps for testing a Page with already created Form with one advance file fields v2.0 field.
- I loaded the page with one advance file field v2.0 field form.
- I attached an image in the advance file field v2.0 and submitted the form successfully
- And the page with one advance file fields v2.0 form was submitted successfully as per my expectations.


**PHP Errors:**
- When I checked the debug.log file of local WordPress test site I didn't see any PHP errors (for a page with Contact Form & for a page with Advance File Field v2.0 field form)

**JavaScript Errors:**
- When I checked the console of my browser,  I didn't see any JavaScript errors. (for a page with Contact Form & for a page with Advance File Field v2.0 field form)

- **According to my initial testing & findings, I didn't saw any bugs for "One of each form on the page" test scenario.**

**Note: This is an initial test finding, I have to test for other two test scenarios to give final conclusion**

WordPress Version: 5.1PHP Version: 7.1.26MySQL Version: 5.7.25Caldera Forms Version: 1.8.1.alpha-1WP_DEBUG: 1

**Comment by guillermoEstudio1640** [comment]
I am having the same problem after updating 1.8.
Tested in Chrome and Explorer. Submit button doesn't load.
This is the Ajax error:

ajax-core.min.js?ver=1.7.5.1:1 Uncaught TypeError: Cannot read property 'CF5c0175f6c700c_1' of undefined
    at Object.init (ajax-core.min.js?ver=1.7.5.1:1)
    at HTMLFormElement.<anonymous> (jquery-baldrick.min.js?ver=1.7.5.1:1)
    at HTMLFormElement.dispatch (jquery.js?ver=1.12.4:3)
    at HTMLFormElement.r.handle (jquery.js?ver=1.12.4:3)

It is an "_1" added to the for shortcode.

I'm sorry if this doesn't helps or is miswritten. This is my first post here (Ia am Cladera Pro user) and I am not a developer. Just trying to fix the issue.

**Comment by guillermoEstudio1640** [comment]
We duplicated the for to solve it

**Comment by xrahat2011** [comment]
I am literally facing this issue! This broke down my whole site's forms and my whole site is based on custom form submissions. :'(

**Comment by Shelob9** [comment]
@xrahat2011 which version are you using? I would recommend rolling back to version 1.7.7 and then updating your staging site to 1.8.2 and then filing a new issue with all of the requested information. That way we can understand what is wrong

**Comment by xrahat2011** [comment]
> I am having the same problem after updating 1.8.
> Tested in Chrome and Explorer. Submit button doesn't load.
> This is the Ajax error:
> 
> ajax-core.min.js?ver=1.7.5.1:1 Uncaught TypeError: Cannot read property 'CF5c0175f6c700c_1' of undefined
> at Object.init (ajax-core.min.js?ver=1.7.5.1:1)
> at HTMLFormElement. (jquery-baldrick.min.js?ver=1.7.5.1:1)
> at HTMLFormElement.dispatch (jquery.js?ver=1.12.4:3)
> at HTMLFormElement.r.handle (jquery.js?ver=1.12.4:3)
> 
> It is an "_1" added to the for shortcode.
> 
> I'm sorry if this doesn't helps or is miswritten. This is my first post here (Ia am Cladera Pro user) and I am not a developer. Just trying to fix the issue.

I have even tried using UNMIFIED version of caldera "https://calderaforms.com/doc/caldera_forms_render_assets_minify/" and still bug stays. :'(

**Comment by Shelob9** [comment]
The files that you are getting the errors on have the query string for version 1.7.5.1. have you cleared all caches?

**Comment by xrahat2011** [comment]
> The files that you are getting the errors on have the query string for version 1.7.5.1. have you cleared all caches?

hi bro, version 1.8.2 fixes it? that was released a few miunutes ago, let me double confirm, if i don't post back this is fixed in 1.8.2

**Comment by Shelob9** [comment]
@xrahat2011 yes, it should. 1.8.0 was big release. We changed a lot of stuff under the hood, help understanding the edge cases we are running into is huge for us and everyone else.

**Pull request merged**
