### PR TITLE
#3083 add 'caldera_forms_calculation_field_get_value' filter

### PR DESCRIPTION
**Pull request by mecachisenros**
Proposal to add `caldera_forms_calculation_field_get_value` filter for filtering calculation field values as per description in #3083

### CODE REVIEW

**Comment by kcristiano** [comment]
@New0 Can you let us know what we nee to do to get this merged in?   We've been running in production since 1.8.7 and would prefer not to have to maintain our own build

**Comment by New0** [comment]
@Shelob9 could you review and also check how we can run CI tests on this branch?

**Comment by Shelob9** [comment]
> @Shelob9 could you review and also check how we can run CI tests on this branch?
@New0 It looks good to me. I don't know how to run CI right for this. Let's merge it, run CI on develop, and if it breaks anything which I doubt it will, we can revert, but also, it's fine.

**Comment by New0** [comment]
Thanks again @mecachisenros

**Pull request merged**
