### PR TITLE
i18n Gettext issues

### PR DESCRIPTION
**Pull request by pedro-mendonca**

### CODE REVIEW

**Comment by New0** [comment]
Hello @pedro-mendonca Thank you for opening this PR and sorry for taking so long. Could you update the branch merging current develop and update .pot file in languages folder ?

**Comment by Shelob9** [comment]
@New0 The changes to the translation functions in this PR look good to me.

I honestly do not get how translations work now. Do we need .po files or does dot org generate them?

**Comment by pedro-mendonca** [comment]
@Shelob9 
For installs from the wp.org repo you don't need .po files, the language packs are served from translate.wp.org.

This PR isn't about language files, but about the code i18n that can be parsed later on by wp.org to generate the strings to translate.

**Comment by pedro-mendonca** [comment]
@New0 I'll rebase the this PR.
Thanks

**Comment by Shelob9** [comment]
@pedro-mendonca Thanks for your contribution, this is great.

> For installs from the wp.org repo you don't need .po files, the language packs are served from translate.wp.org.
That's what I thaught.

> This PR isn't about language files, but about the code i18n that can be parsed later on by wp.org to generate the strings to translate.

Right. @New0 if this is fine in terms of gitflow, then let's merge it.

**Comment by New0** [comment]
@Shelob9 I still think it would make sense to have the generic .pot file up to date with translatable strings when they are updated, I'll update that as a separate PR.

Thanks again  @pedro-mendonca, once you merge current develop in that branch (I did it locally to test and it didn't create conflicts but I can't push to your branch), I'll merge the PR for 1.8.9

**Comment by pedro-mendonca** [comment]
Just rebased on top of develop branch with zero conflicts.
You're safe to go from here :)

**Comment by New0** [comment]
Great Thank you again @pedro-mendonca

**Pull request merged**
