### PR TITLE
initial work for checkbox field - multiple default options support

### PR DESCRIPTION
**Pull request by diegoliv**
@Shelob9 this is a draft for allowing support of multiple default options on the checkout field using the `caldera_forms_render_get_field` filter. On my tests it worked fine without errors. The only thing that I couldn't make it work so far is the calculation fields. When multiple checkboxes are set as default, a calculation field for this checkbox stays at 0. Any tips on where can I check to update the js function that calculates these values?

### CODE REVIEW

**Comment by Shelob9** [comment]
@diegoliv Thanks for submitting this. It looks pretty good so far. 2 notes:

1) Pull request will need to go against the develop branch, not master.
2) This isn't php 5.2 compatible, no closures can be used, sorry, https://github.com/CalderaWP/Caldera-Forms/pull/2287/files#diff-3cfc622349ecd2de00ff0e45a5c7534aR414

**Comment by diegoliv** [comment]
@Shelob9 got it, just changed the branch to develop and made the code 5.2 compatible. Let me know what you think. We still need to figure out the calculation fields.

**Comment by Shelob9** [comment]
@diegoliv Sorry, been so, busy I missed your question. Sorry, look here: https://github.com/CalderaWP/Caldera-Forms/blob/master/classes/field/js.php#L755 That class sets up the data used to initialize front-end JS for field. The method I linked to handles "calc_defaults" -- the default value of a field for the calculation. You'll see there are special rules for checkboxes and calculation fields there.

**Comment by Shelob9** [comment]
That was an accidental closing, sorry.

**Comment by Shelob9** [comment]
@diegoliv  I'd love to see this included. The problem is you're trying to merge your master into our develop. That's going to be a problem. The best thing to do would be to checkout your develop branch, create a branch off of that and then submit a PR of that branch against our develop brach.

**Comment by diegoliv** [comment]
@Shelob9 sure, sorry for the confusion! I'm gonna work on this later today and will submit the PR again.

**Pull request closed without merging**
