### PR TITLE
Fix CSV export of checkbox fields

### PR DESCRIPTION
**Pull request by Shelob9**
Resolves - #2895

@New0 You can disagree, but I'm not adding a unit test. I'd have to rewrite all exports of CSVs first. And that's something we will be doing soon, but not before 1.8.0.

### CODE REVIEW

**Comment by New0** [comment]
Replaced by PR https://github.com/CalderaWP/Caldera-Forms/pull/2930

**Comment by Shelob9** [comment]
>It didn't work for me and wasn't sure that all the changes concerned the issue
As we discussed today, @New0 was testing the CSV attached to the email. The issue, and this was not clear at all, was that the CSV export from entry viewer had the encoded checkboxes.

I am re-opening this PR and closing #2930

**Comment by Shelob9** [comment]
I effectively copied PR #2930 into here via c67059a

I searched for usages of the function that changes. I don't see any reason to be concerned. 
screen shot 2019-01-29 at 12 59 39 pm

Let's make sure that the export form we have in #888 still works as expected before merging https://github.com/CalderaWP/Caldera-Forms/issues/888#issuecomment-255471271

**Comment by Shelob9** [comment]
@swapnilmanjrekar Can you please check this branch to ensure it resolves #2895 without re-introducing #888.

This file has two form exports:
[2895-forms.zip](https://github.com/CalderaWP/Caldera-Forms/files/2809017/2895-forms.zip)

For the file 2895.json file, please submit the form with 1 checkbox option checked, and then again with 3 options checked. Make sure you have mailhog set to get emails -- you may need to enable mailer on these form exports.

Then make sure that:
1) The email summary contains the options you selected, separated by commas and no JSON-encoded data.
2) Check that the entry viewer has the options you selected, separated by commas and no JSON-encoded data.
3) Use the entry viewer to export all entries of the form. Make sure that each entry has he options you selected, separated by commas and no JSON-encoded data.

Please repeat with form 888.json, following the same steps and ensuring that the issue describe in #888 is not recurring.

**Comment by swapnilmanjrekar** [comment]
@Shelob9 I tested this on my local WordPress test site. I Imported 2895 form and 888 forms that you provided me. Form 888 successfully met all the 3 Scenarios that you provided to test, form 2895 met successfully the 1& 2 Sceanrio's but for form 2895, when I was exporting all the entries of form and opened the 2895.csv file it was only showing the entrie's date and time but no entries as I expected to see entries in the 2895.csv file.

2895csv

WordPress Version: 5.0.3PHP Version: 7.1.26MySQL Version: 5.7.25Caldera Forms Version: 1.8.0-alpha.1WP_DEBUG: 1

**Comment by New0** [comment]
@Shelob9 
With Form 2895 \:
1. the emails shows the options correctly, coma-separated without json
2. but the entry viewer only shows one result when multiple options are checked on the checkbox field ( without json )
3. the CSV export didn't show any option and was empty

With Form 888 \:
1. At first the checkbox fields were not listed in the email as expected, I added the {summary} in the email and the options were listed correctly
2. The options are shown twice in the entry viewer as Option 1 (Option 1), Option 4 (Option 4) 
3. The options were correctly listed in the csv export file

**Comment by Shelob9** [comment]
@new0 a note on your testing of form 888 -> `* The options are shown twice in the entry viewer as Option 1 (Option 1), Option 4 (Option 4)` That's correct, it should show Label (Value) or the other way around. In this case label and value are the same.

**Comment by Shelob9** [comment]
I got the same problem as @New0 did with form 2895, that has a checkbox field where the values are 1,2 and 3. I added another field with the values of One, Two and Three and it works as expected.

screen shot 2019-02-13 at 8 06 05 am

**Comment by Shelob9** [comment]
@New0 OMG(S) - There is the correct, formatted value in the array. I already solved this problem.

screen shot 2019-02-13 at 8 22 19 am

I'm putting in the quick fix, but the correct refactor I believe is this: https://refactoring.com/catalog/replaceArrayWithObject.html

**Comment by Shelob9** [comment]
@New0  With c8b7277 we get the correctly formatted "view" value for the field whenever possible. IF that's not the right value to use, then that's a separate bug. But that is what email, and entry viewer SHOULD be using as well.

**Comment by New0** [comment]
@Shelob9 in my last tests, all the tests pass except one scenario =>

When the option Value and Label are a number and the same number, only one option shows up in the entry viewer and csv export even when multiple options were checked. It works as expected in emails and csv attached to emails.

**Comment by New0** [comment]
@Shelob9 the value of the checkbox field is correctly displayed in the entry preview \:
screenshot_2019-02-14 caldera forms admin dev wordpress

This only happens in the entry viewer \:
screenshot_2019-02-14 caldera forms admin dev wordpress 1

I find the value is displayed L359 in ui/entries/scripts_templates.php by "view" variable

**Comment by Shelob9** [comment]
@new0 I suspect the problem is we've tried to fix this 5 ways. Most likely all we actually need is what I did in my last commit and we should back out of the rest. https://github.com/CalderaWP/Caldera-Forms/commit/c8b72772715c561044b2baf3299abd8131fc40c9

**Comment by New0** [comment]
> 
> 
> @New0 I suspect the problem is we've tried to fix this 5 ways. Most likely all we actually need is what I did in my last commit and we should back out of the rest. [c8b7277](https://github.com/CalderaWP/Caldera-Forms/commit/c8b72772715c561044b2baf3299abd8131fc40c9)

@Shelob9 I agree, with your approval I'm going to merge this PR and open a separate issue for the case I describe earlier. Which is a separate and precise issue. Let me know if you approve

**Comment by Shelob9** [comment]
Yes. Put new issue on 1.8.1

**Pull request merged**
