### PR TITLE
Fix for PHP Deprecated: Function create_function() is deprecated

### PR DESCRIPTION
**Pull request by waattt**
The create_function was preventing my forms to be submitted on PHP 7.2, so I rewrote the create_function to an anonymous function.

I tried to see if this was fixed somewhere before, but no result. This is my first pull request, so my apologies if I saw it wrong!

### CODE REVIEW

**Comment by Shelob9** [comment]
@waattt OMG(S)  I have not tested this, but this looks really smart. I had a different solution in mind that was may more complex.

>I tried to see if this was fixed somewhere before, but no result. This is my first pull request, so my apologies if I saw it wrong!
This is an epic first Pull Request! So we have a long list of steps we have to follow for a PR here - https://github.com/CalderaWP/Caldera-Forms/blob/master/CONTRIBUTING.md#step-by-step If you want to go through them with us, we use a workflow that is common for medium to large codebases and maybe that's fun/ valuable for you. Or we can just modify this PR to work the way we need it to. Either way we give you tons of credit :)

@New0 Let's discuss tomorrow. I don't want to put more 1.8.0 things on, but this would delete an entire class of bugs with calculation fields without rewriting them from scratch, which I'm going to do, but not this week.

**Comment by Shelob9** [comment]
@swap_wp  Can you please find issues related to calculation fields creating deprecated notices or causing forms not to submit. Please leave a comment with the issue number for each issue you find.

**Comment by Shelob9** [comment]
I changed the branch to be merged to from `master` to `develop` looks clean.

**Comment by Shelob9** [comment]
@swap_wp I wrote up the QA that is needed for this and assigned to you here: https://app.asana.com/0/874513965099411/982043784084561

**Comment by swapnilmanjrekar** [comment]
**I tested this bug using the following steps:**

- I created a WordPress test site on my desktop locally using Lando.
- I installed CF plugin on my test site.
- Using the CF plugin, I imported a "1962" form.
- When the calculation was done after selecting the dropdown field, checkbox field and radio field after dividing it by 1 and increment by 9 i.e 10 on step count it gave proper calculations for divding by even number step but for the odd number it gave calculations with answers like e.g "21.05263157894737" but instead I expected "21.05"
- Also when I clicked on the submit button, it showed me "calculation is invalid" warning.

**JavaScript Errors:**

- When I checked the console of my web browser I didn’t see any javascript errors.

**PHP Errors:**

- When I checked the debug.log file of my WordPress test site It showed the following error:
 "PHP Warning:  is_infinite() expects parameter 1 to be float, string given in /app/wp-content/plugins/1.8.0-alpha.1/classes/core.php on line 1450"



WordPress Version: 5.0.3PHP Version: 7.1.25MySQL Version: 5.7.24Caldera Forms Version: 1.8.0-alpha.1WP_DEBUG: 1

**Comment by Shelob9** [comment]
@swapnilmanjrekar Good catch, I think that is a prexisting and easily fixable bug. 

We agreed that if we find any bugs in this, we will push to 1.8.1 and fix then, else we will put on 1.8.0 and merge nowish.

**Comment by swapnilmanjrekar** [comment]
**I tested this bug using the following steps:**

- I created a WordPress test site on my desktop locally using Lando.
- I installed CF plugin on my test site.
- Using the CF plugin, I imported a "1979" form.
- When I selected the checkbox option from selections field, total, subtotal field, the calculations were done perfectly as I expected to see.
- But when I clicked on the submit button, it showed me "calculation is invalid" warning which was unexpected as I expected it to show me form submitted successfully message.

**JavaScript Errors:**

- When I checked the console of my web browser I didn’t see any javascript errors.

**PHP Errors:**

- When I checked the debug.log file of my WordPress test site It showed the following error:
- "PHP Notice:  A non well formed numeric value encountered in /app/wp-content/plugins/1.8.0-alpha.1/classes/core.php on line 1450"
- "PHP Warning: is_infinite() expects parameter 1 to be float, string given in /app/wp-content/plugins/1.8.0-alpha.1/classes/core.php on line 1450"




- **So According to my findings, this is a bug as after calculation when I clicked the submit button it was showing "calculation is invalid" warning.**


WordPress Version: 5.0.3PHP Version: 7.1.25MySQL Version: 5.7.24Caldera Forms Version: 1.8.0-alpha.1WP_DEBUG: 1

**Comment by swapnilmanjrekar** [comment]
**I tested this bug using the following steps:**

- I created a WordPress test site on my desktop locally using Lando.
- I installed CF plugin on my test site.
- Using the CF plugin, I imported a "1993" form.
- When I selected the option from Number 1 and Number2 field, the calculations were done perfectly as I expected to see.
- But when I clicked on the submit button, it showed me "calculation is invalid" warning which was unexpected as I expected it to show me form submitted successfully message.

**JavaScript Errors:**

- When I checked the console of my web browser I didn’t see any javascript errors.

**PHP Errors:**

- When I checked the debug.log file of my WordPress test site It showed the following error:
  "PHP Warning: is_infinite() expects parameter 1 to be float, string given in /app/wp-content/plugins/1.8.0-alpha.1/classes/core.php on line 1450"

- **So According to my findings, this is a bug as after calculation when I clicked the submit button it was showing "calculation is invalid" warning.**

WordPress Version: 5.0.3PHP Version: 7.1.25MySQL Version: 5.7.24Caldera Forms Version: 1.8.0-alpha.1WP_DEBUG: 1

**Comment by swapnilmanjrekar** [comment]
**I tested this bug using the following steps:**

- I created a WordPress test site on my desktop locally using Lando.
- I installed CF plugin on my test site.
- Using the CF plugin, I imported a "x3" form.
- When I enter a number in number field, the calculations were not done perfectly as I expected to see
   number 73 to rounded to it nearest ten i.e 70 but it showing me the rounded value as "1" which was 
   not as per expectations.
- Also when I clicked on the pay button, it showed me "calculation is invalid" warning which was 
   unexpected as I expected it to show me form submitted successfully message.

**JavaScript Errors:**

- When I checked the console of my web browser I didn’t see any javascript errors.

**PHP Errors:**

- When I checked the debug.log file of my WordPress test site It showed the following error:
  "PHP Warning: is_infinite() expects parameter 1 to be float, string given in /app/wp-content/plugins/1.8.0-alpha.1/classes/core.php on line 1450"

- **So According to my findings, this is a bug as after calculation when I clicked the submit button it was showing incorrent rounding of a number & also "Calculation is invalid" warning.**

WordPress Version: 5.0.3PHP Version: 7.1.25MySQL Version: 5.7.24Caldera Forms Version: 1.8.0-alpha.1WP_DEBUG: 1

**Comment by Shelob9** [comment]
Issue #2335
Related: #2788

**Comment by Shelob9** [comment]
Ok, I tested this with the form for the tests from #1979  and set a breakpoint where the "calculation is invalid" error is created:

screen shot 2019-01-18 at 2 59 00 pm

The total function is returning the formula as a string. We would still need to parse it with `eval()`... I am moving this to 1.8.1

**Comment by Shelob9** [comment]
https://github.com/chriskonnertz/string-calc

**Comment by Shelob9** [comment]
This did not do the math as needed. We are working on a new option.

**Pull request closed without merging**
