### PR TITLE
fix Phone (better) field 'Not a number' validation error message

### PR DESCRIPTION
**Pull request by mecachisenros**
Issue described here #2703

### CODE REVIEW

**Comment by Shelob9** [comment]
@mecachisenros Thanks for this PR. The file you're modifying is a generated file, so if I merged this, it would be immediately lost. That function is here:
https://github.com/CalderaWP/Caldera-Forms/blob/master/assets/js/field-config.js#L383

You can get CF to load that file with this filter: https://calderaforms.com/doc/caldera_forms_render_assets_minify/

**Comment by Shelob9** [comment]
Hopefully this can fix #2652 as well

**Comment by mecachisenros** [comment]
@Shelob9 thank you for the heads up, I did not see the `/*! GENERATED SOURCE FILE */` 😄 
I've amended the commit, so this should be ready to merge.

Unfortunately it does not fix #2652, I'll have a look see if I find a fix for it.

**Comment by Shelob9** [comment]
@New0 Can you please test this now that #2711 is merged ?

**Comment by Shelob9** [comment]
@mecachisenros @New0 It looks like the conditional logic is not reinitalizing after the field is hidden, then unhidden by conditional logic.

Two theories:
1) The init function is not running after the field is re-added, which should happen beacuse of this binding to `cf.add` event:
https://github.com/CalderaWP/Caldera-Forms/blob/5eb23f08e14e453702f063630d2870eff10b5df9/assets/js/field-config.js#L450

2) Something changed re: WHEN the `cf.add` event runs, so it doesn't reinit the field, which I don't think so but FML if that's the problem.

3) It's running the init() function with bad arguments or before the field is back on the DOM after conditional logic unhides the field.

**Comment by Shelob9** [comment]
@New0  I pushed commits for the issues we found while discussing this - validation not triggered after unsave and button not releasing.

Can you please re-review?

**Comment by New0** [comment]
@Shelob9 I ran tests with and without assets minified and the field had the same behavior we saw on your screen.

- The 'not a number message shows correctly before the condition hides the phone field, but when the condition shows back the phone field ->
    1 the 'not a number' is not displayed
    2 the submit button was re-enabled
    3 I was able to submit the form

- The only difference I found when setting the phone field as required is that the submit button is disabled before the phone field gets hidden, when the phone fields is shown back, the submit button was enabled again and I was able to submit.

**Comment by Shelob9** [comment]
@New0 Check this out:
https://github.com/CalderaWP/Caldera-Forms/blob/master/assets/js/conditionals.js#L308-L315

`cf.add` gets triggered and THEN the value gets restored to the field. So sequence of events is now:

1) Place field on DOM with NO value set
2) Trigger `cf.add`
3) Rerun validation
4) Reset the stored value to the field.

If 3 and 4 were reversed this would make sense, as is its madeness. I'm afraid to modify conditionals.js

**Comment by Shelob9** [comment]
My solution is when cf.add is triggered, to bind to the state update event, trigger init and then remove that event. That way the initialization and validation runs once the value is reset. I remove it to prevent it from reinitializing on every change event to the phone field.

**Comment by Shelob9** [comment]
@New0 Please review again. Also, do you have a good solution for the merge conflicts in generated files?

**Comment by New0** [comment]
@Shelob9 I added the validation on the submit button click, I think the validation we intend to do at field-config.js l 441 happens too late, the form submit event already started

This works for submission but that can create issue for multi page forms as it doesn't work for next page button click event.

**Comment by Shelob9** [comment]
@New0 Can you solve this by adding events on page forward and back? if so, please add those events.

**Comment by New0** [comment]
@Shelob9 I couldn't find a solution by triggering a custom event during the .on click event that is already set up. 
I set a .click event in the field-configs, I tested with multiple phone fields and multiple forms in the page. Could you review ?

**Comment by kcristiano** [comment]
@Shelob9 This is quite a critical fix for a number of our sites, can you let us know what (if anything) we can do to help move this along?

**Comment by New0** [comment]
@kcristiano testing this branch on a staging environment of your websites and reporting back would help. To do so, it would require to rebuild the dependencies using composer.

Otherwise, wait Josh review and test the develop branch when this PR will be merge.

**Comment by New0** [comment]
@kcristiano this is a development branch, it is not ready for production. The working patch was introduced yesterday, I strongly advise to switch back to master branch for production and wait for this branch to be merged to master, this is when we'll run all final tests and push the master branch to WordPress.org repository

**Comment by kcristiano** [comment]
Thanks @Shelob9 I was not looking to give anyone grief on the time it took, I know it was complicated and appreciate the work.  I was trying to explain why we needed to move the PR to production.  I much prefer to run on the stable branch.

**Pull request merged**
