### PR TITLE
Allow integers as option ID for custom autopopulated checkboxes

### PR DESCRIPTION
**Pull request by mecachisenros**
As per my description in #2849 this will allow custom autopopulated Checkbox fields to be calculated when used as an Operator in a Calculation field.

### CODE REVIEW

**Comment by Shelob9** [comment]
@mecachisenros  Thanks for the PR. We need  to add one test before this can be merged.

Test will need a checkbox field with options like this:

`[ config => options => [ 'opt12345' => [ 'value' => 1 ],  2 => => [ 'value' => 2 ] ]`

Then it will test
* Given that form with an option like the one above -- one option with a numeric option ID of the string `opt12345` and an option ID of integer `2`, when calling `Caldera_Forms_Field_Util ::get_option_calculation_value()` 

* assert that the filter `caldera_forms_get_option_calculation_value ` is called twice.

**Comment by mecachisenros** [comment]
@Shelob9 thank you.

Could you point me to the test file where I should write the test?

**Comment by Shelob9** [comment]
@mecachisenros Tests would be written here: https://github.com/CalderaWP/Caldera-Forms/tree/develop/tests

**Comment by Shelob9** [comment]
@mecachisenros I should clarify, php unit tests for the function you modified would go there. That doesn't cover the front-end JS preview. We would need a cypress test for that - https://github.com/CalderaWP/Caldera-Forms/tree/develop/cypress

**Comment by Shelob9** [comment]
@New0  has tested this manually with this filter https://gist.github.com/New0/43675dc394fef1510eba33668b7dcf5f

I did the same test, just modified the field ids in the code and it worked as expected.

**Pull request merged**
