### PR TITLE
Add interface & base class to support future CRM processors

### PR DESCRIPTION
**Pull request by shawnhooper**

### CODE REVIEW

**Comment by Shelob9** [comment]
@shawnhooper I don't think the methods in this class are needed, since they exist in the class they are extending.

**Comment by shawnhooper** [comment]
@Shelob9 Yup, good point.  That was a copy/paste from the newsletter processor.  No actual CRM processor to test this against yet, just wanted the class name there to extend from.

**Comment by Shelob9** [comment]
#1619

**Comment by Shelob9** [comment]
@shawnhooper The @since should be 1.5.1 otherwise Taco Emoji

**Comment by shawnhooper** [comment]
@Shelob9 You may proceed with Taco emoji.

**Pull request merged**
