### PR TITLE
Remove the magic tags from the options label

### LINKED ISSUE #3167: PHP Fatal error: Uncaught TypeError: Argument 2 passed to Caldera_Forms_Field_Util::has_field_type() must be of the type array, null given
On the default install of caldera if I try to view an entry it returns the following PHP Error
PHP Fatal error: Uncaught TypeError: Argument 2 passed to Caldera_Forms_Field_Util::has_field_type() must be of the type array, null given

It happens when there is something url encoded in the label of a an option (Eg: %C3%C3) (If you put a link inside the label for example)
That's because the option label tries to apply magic tags when it shouldn't

I tracked it down to the method format_select_options in core.php and the call to `self::do_magic_tags($option['label']);`

Why is the label magic tagged? There is no point in it is there? Anyway even if there was it would cause an error when viewing the entry because the form global is not defined at this point and would throw this error

### PR DESCRIPTION
**Pull request by Tofandel**
Fixes #3167

### CODE REVIEW

**Comment by Tofandel** [comment]
> I can imagine scenarios where magic tags are used in options labels or values, like getting data from a previous page

The point is, it's not possible, if that was the case you'd get a fatal php error ;)

> Also, I'm not sure why you want to use an url in url encoded format in the option label but in this case I would first try using the 'caldera_forms_render_get_field' filter hook to format the option label as needed, you can read more about that hook at https://calderaforms.com/doc/caldera_forms_render_get_field/

It's quite a frequent use case, you can insert html in the label so if you have an <a> tag with a link in the label you will run into the error

**Comment by Tofandel** [comment]
Related https://github.com/CalderaWP/Caldera-Forms/issues/3157

**Comment by New0** [comment]
@Tofandel Thank you for the explanation, I missed the point that it was related to the entry viewer. I opened #3207 that address that issue. Magic tags in the option label working on frontend, I still believe we can't just remove them.

Also in the case you use a link in the option label, I'm not sure you need to url encode it.

**Comment by Tofandel** [comment]
You don't always have control over the url, for me it's my client who is usually creating them, he his just copy pasting the url and putting it in the `<a href="url">` since it's in an html parameter and if there is special characters in it (like quotes or spaces) it has to be url encoded, also when you copy it from chrome you get it url encoded anyway

**Comment by Shelob9** [comment]
>You don't always have control over the url, for me it's my client who is usually creating them, he his just copy pasting the url and putting it in the <a href="url"> since it's in an html parameter and if there is special characters in it (like quotes or spaces) it has to be url encoded, also when you copy it from chrome you get it url encoded anyway

In my opinion, this is not something we should support via magic tags. It's an edge case that's hard to control for securely. We'd have to detect if it is a link and if so what steps were need to escape it properly. I think using the `caldera_forms_render_get_field` to solve that specific issue makes more sense.

Something like:

```
add_filter( 'caldera_forms_render_get_field', function( $field )  {
    if( 'fld...' == $field[ 'ID' ] ){
        $url = function_that_determines_url_you_need();
        if( filter_var($url, FILTER_VALIDATE_URL ) ){
            $field[ 'config' ][ 'label' ] = '<a href="' . esc_url( urlencode($url ) ) . '">Text</a>';
            
        }
    }
    return $field;
});
```

https://calderaforms.com/doc/caldera_forms_render_get_field/

**Comment by Shelob9** [comment]
@new0 Should we close this now that  #3207 is merged?

**Pull request closed without merging**
